server:
  port: 8888

spring:
  jmx:
    enabled: false

logging:
  level:
#    org.springframework.cloud.gateway: TRACE
#    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
#    reactor.ipc.netty: DEBUG

management.endpoints.web.exposure.include: '*'